sudo: required

services:
  - docker

matrix:
  include:
    - env: BUILD_PATH="./7/jre" IMAGE_TAG="bestwu/java:7"
    - env: BUILD_PATH="./7/jdk" IMAGE_TAG="bestwu/java:jdk7"
    - env: BUILD_PATH="./8/jre" IMAGE_TAG="bestwu/java:8"
    - env: BUILD_PATH="./8/jdk" IMAGE_TAG="bestwu/java:jdk8"

script:
  - docker build $BUILD_PATH -t $IMAGE_TAG
  - docker run --rm $IMAGE_TAG java -version